version: '3.9'
services:
  rollee-task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: postgres
    # ports:          # Expose postgres port.
    #   - '5432:5432' #
    environment:
      POSTGRES_DB: rollee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
